apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - api-deployment.yaml
  - portal-deployment.yaml
  - mcp-deployment.yaml
  - workers-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: opencortex
  app.kubernetes.io/managed-by: kustomize
